import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PUBLIC_OPPORTUNITY_CATEGORIES, getPublicOpportunityCategory } from "@/lib/seo/public-opportunity-categories";
import { resolveGroundingSources } from "@/lib/platform/nia-grounding";
import { SITE_URL } from "@/lib/seo/public-content";
export const dynamicParams = false;
export function generateStaticParams(){return PUBLIC_OPPORTUNITY_CATEGORIES.map((item)=>({category:item.slug}));}
export async function generateMetadata({params}:{params:Promise<{category:string}>}):Promise<Metadata>{const{category}=await params;const item=getPublicOpportunityCategory(category);if(!item)return{};return{title:`${item.title} | Beginly`,description:item.summary,alternates:{canonical:`${SITE_URL}/opportunity-categories/${item.slug}`},openGraph:{title:item.title,description:item.summary,url:`${SITE_URL}/opportunity-categories/${item.slug}`,type:"website"}};}
export default async function OpportunityCategoryPage({params}:{params:Promise<{category:string}>}){const{category}=await params;const item=getPublicOpportunityCategory(category);if(!item)notFound();const sources=resolveGroundingSources(item.sourceIds);const jsonLd={"@context":"https://schema.org","@type":"WebPage",name:item.title,description:item.summary,url:`${SITE_URL}/opportunity-categories/${item.slug}`,dateModified:item.reviewDate,isPartOf:{"@type":"WebSite",name:"Beginly",url:SITE_URL}};return <main className="public-content-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header><span>Trust-led opportunity category</span><h1>{item.title}</h1><p>{item.summary}</p></header><section><h2>What Beginly checks</h2><ul>{item.trustChecks.map((check)=><li key={check}>{check}</li>)}</ul></section><section><h2>Source and review authority</h2><p>Reviewed for publication through {new Date(item.reviewDate).toLocaleDateString("en-GB")}.</p><ul>{sources.map((source)=><li key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> · {source.authority}</li>)}</ul></section><section className="public-content-callout"><h2>Open your private Opportunity Radar</h2><p>Recommendations are ranked using route fit, geography, timing, readiness and trust. Commission does not increase suitability.</p><Link href="/signup">Create an account</Link><Link href="/opportunity-categories">View all categories</Link></section></main>;}
