import PlatformShell from "@/components/platform/PlatformShell";
import ModuleCard from "@/components/platform/ModuleCard";
import StatusPill from "@/components/platform/StatusPill";
import AdaptiveCheckIn from "@/components/platform/AdaptiveCheckIn";
import { composeDashboard } from "@/lib/platform/dashboard";
import { buildJourney } from "@/lib/platform/journey";
import { loadCurrentPlatformContext } from "@/lib/platform/server-context";
import { ArrowRight,CheckCircle2,Compass,Route,Sparkles } from "lucide-react";
import Link from "next/link";
export const dynamic="force-dynamic";
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
export default async function PlatformPage(){const context=await loadCurrentPlatformContext();const dashboard=composeDashboard(context);const journey=buildJourney(context);const average=Math.round(journey.readiness.reduce((sum,item)=>sum+item.score,0)/Math.max(1,journey.readiness.length));const sponsored=context.grants.find(grant=>grant.source==="sponsor");const nextHorizon=journey.forecast[0]?.label??"Your next transition";return <PlatformShell title={`How are you feeling today, ${context.displayName.split(" ")[0]}?`} eyebrow="Your adaptive Today view" action={sponsored?<StatusPill tone="sponsored">Sponsored access active</StatusPill>:<StatusPill tone="positive">Free adaptivity active</StatusPill>}><section className="platform-hero-card"><div><span className="platform-eyebrow"><Sparkles size={15}/> Beginly is preparing the next transition</span><h2>Your current route, goals, household, opportunities and access are interpreted together.</h2><p>Beginly keeps your history as your route and life stage change. Paid support adds execution depth without replacing the adaptive free foundation.</p><div className="platform-hero-actions"><Link href="/journey" className="platform-primary">Continue my journey <ArrowRight size={17}/></Link><Link href="/nia" className="platform-secondary">Ask Nia</Link></div></div><div className="platform-readiness-orbit"><div><strong>{average}%</strong><span>overall readiness</span></div><i/><b/></div></section><div className="platform-context-strip"><div><Route size={18}/><span>Current route</span><b>{label(context.route)}</b></div><div><Compass size={18}/><span>Current stage</span><b>{label(context.stage)}</b></div><div><CheckCircle2 size={18}/><span>Next horizon</span><b>{nextHorizon}</b></div></div><section className="platform-section-heading"><div><span>Composed for your context</span><h2>Today</h2></div><p>{dashboard.explanation}</p></section><AdaptiveCheckIn /><div className="platform-module-grid">{dashboard.modules.map(module=><ModuleCard key={module.id} module={module}/>)}</div></PlatformShell>}
