import type { CapabilityDefinition, Opportunity, ProductDefinition } from "./types";

export const CAPABILITIES: CapabilityDefinition[] = [
  { code: "adaptive_journey", name: "Adaptive journey", description: "Route and stage-aware next actions.", freeCore: true },
  { code: "basic_nia", name: "Nia guidance", description: "Contextual, safety-aware guidance.", freeCore: true },
  { code: "basic_opportunities", name: "Opportunity discovery", description: "Relevant and explainable opportunities.", freeCore: true },
  { code: "household_basic", name: "Basic household", description: "Shared household profile and tasks.", freeCore: true },
  { code: "readiness_score", name: "Readiness score", description: "Explainable readiness dimensions.", freeCore: true },
  { code: "career_journey", name: "Career journey", description: "Career preparation and progression plan." },
  { code: "cv_studio", name: "CV Studio", description: "Role-specific CV preparation and review." },
  { code: "interview_studio", name: "Interview Studio", description: "Structured interview practice and feedback." },
  { code: "application_tracker", name: "Application tracker", description: "Organise applications, deadlines and outcomes." },
  { code: "sponsor_readiness", name: "Sponsor readiness", description: "Prepare for sponsorship-oriented opportunities." },
  { code: "radar_premium", name: "Opportunity Radar Premium", description: "Continuous monitoring and advanced alerts." },
  { code: "family_workspace", name: "Family workspace", description: "Household coordination with private member workspaces." },
  { code: "founder_evidence", name: "Founder evidence room", description: "Evidence, milestones and endorsement readiness." },
  { code: "readiness_report", name: "Readiness report", description: "Exportable personalised readiness assessment." },
  { code: "document_organisation", name: "Document organisation", description: "Structured, private document checklist and metadata." },
  { code: "advanced_nia", name: "Advanced Nia", description: "Monitoring, preparation and permissioned proposals." },
  { code: "human_review", name: "Human review", description: "Qualified human review where available." },
  { code: "commission_programme", name: "Commission programme", description: "Offer, attribution, conversion and reconciliation tools." },
];

export const PRODUCTS: ProductDefinition[] = [
  {
    id: "free_os",
    name: "Beginly Free OS",
    promise: "Deeply adaptive settlement, transition and opportunity guidance without an irrelevant-feature tax.",
    kind: "free",
    capabilities: ["adaptive_journey", "basic_nia", "basic_opportunities", "household_basic", "readiness_score"],
    routeFit: "all",
    scope: "individual",
    autonomyLevel: 1,
    priceMinor: 0,
    currency: "GBP",
    billingInterval: "free",
    standalone: true,
    featured: true,
  },
  {
    id: "career_pro",
    name: "Career Pro",
    promise: "A longitudinal career workspace from readiness to applications, interviews and progression.",
    kind: "subscription",
    capabilities: ["career_journey", "cv_studio", "interview_studio", "application_tracker", "sponsor_readiness", "advanced_nia"],
    routeFit: ["student", "graduate", "skilled_worker", "health_care", "family_dependant"],
    scope: "individual",
    autonomyLevel: 4,
    priceMinor: 1900,
    currency: "GBP",
    billingInterval: "month",
    standalone: true,
    featured: true,
  },
  {
    id: "cv_studio",
    name: "CV Studio",
    promise: "Focused CV preparation when a broader subscription is unnecessary.",
    kind: "standalone",
    capabilities: ["cv_studio"],
    routeFit: ["student", "graduate", "skilled_worker", "health_care", "family_dependant"],
    scope: "individual",
    autonomyLevel: 3,
    priceMinor: 1200,
    currency: "GBP",
    billingInterval: "one_off",
    standalone: true,
  },
  {
    id: "interview_studio",
    name: "Interview Studio",
    promise: "Focused interview preparation, practice and structured reflection.",
    kind: "standalone",
    capabilities: ["interview_studio"],
    routeFit: ["student", "graduate", "skilled_worker", "health_care", "family_dependant"],
    scope: "individual",
    autonomyLevel: 3,
    priceMinor: 900,
    currency: "GBP",
    billingInterval: "one_off",
    standalone: true,
  },
  {
    id: "family_workspace",
    name: "Family Workspace",
    promise: "Coordinate shared settlement and family actions while preserving each adult's private work.",
    kind: "subscription",
    capabilities: ["family_workspace", "document_organisation", "advanced_nia"],
    routeFit: ["student", "skilled_worker", "health_care", "family_dependant", "founder"],
    scope: "household",
    autonomyLevel: 3,
    priceMinor: 1500,
    currency: "GBP",
    billingInterval: "month",
    standalone: true,
    featured: true,
  },
  {
    id: "opportunity_radar_premium",
    name: "Opportunity Radar Premium",
    promise: "Continuous, high-fit opportunity monitoring with readiness gaps and deadline alerts.",
    kind: "subscription",
    capabilities: ["radar_premium", "advanced_nia"],
    routeFit: "all",
    scope: "individual",
    autonomyLevel: 4,
    priceMinor: 1000,
    currency: "GBP",
    billingInterval: "month",
    standalone: true,
  },
  {
    id: "founder_evidence",
    name: "Founder Evidence & Readiness",
    promise: "Build and govern innovation, viability, scalability and execution evidence in one workspace.",
    kind: "subscription",
    capabilities: ["founder_evidence", "readiness_report", "document_organisation", "advanced_nia"],
    routeFit: ["founder", "global_talent"],
    scope: "individual",
    autonomyLevel: 4,
    priceMinor: 2900,
    currency: "GBP",
    billingInterval: "month",
    standalone: true,
    featured: true,
  },
  {
    id: "readiness_report",
    name: "Personal Readiness Report",
    promise: "A one-off, exportable account of strengths, gaps and next actions.",
    kind: "standalone",
    capabilities: ["readiness_report"],
    routeFit: "all",
    scope: "individual",
    autonomyLevel: 2,
    priceMinor: 700,
    currency: "GBP",
    billingInterval: "one_off",
    standalone: true,
  },
  {
    id: "ultimate_transition",
    name: "Ultimate Transition",
    promise: "A flexible bundle for users who genuinely need career, family, opportunity and advanced Nia capabilities together.",
    kind: "bundle",
    capabilities: ["career_journey", "cv_studio", "interview_studio", "application_tracker", "sponsor_readiness", "radar_premium", "family_workspace", "advanced_nia", "readiness_report"],
    routeFit: "all",
    scope: "household",
    autonomyLevel: 5,
    priceMinor: 3900,
    currency: "GBP",
    billingInterval: "month",
    standalone: true,
  },
  {
    id: "commission_readiness",
    name: "Commission Readiness Infrastructure",
    promise: "Turn a suitable business into an attribution, conversion and reconciliation-ready partner programme.",
    kind: "business",
    capabilities: ["commission_programme"],
    routeFit: "all",
    scope: "organisation",
    autonomyLevel: 4,
    priceMinor: 4900,
    currency: "GBP",
    billingInterval: "month",
    standalone: true,
  },
];

const now = new Date();
const daysFromNow = (days: number) => new Date(now.getTime() + days * 86_400_000).toISOString();

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "11111111-1111-4111-8111-111111111101",
    title: "Project Delivery Internship Programme",
    provider: "Northbridge Projects",
    category: "job",
    description: "A structured project delivery placement with mentoring, portfolio evidence and potential progression.",
    routes: ["student", "graduate", "family_dependant"],
    cities: ["Leeds", "Manchester", "Sheffield"],
    goalTags: ["job", "experience", "project management"],
    trustScore: 0.91,
    readinessRequirements: ["cv_studio", "interview_studio"],
    deadline: daysFromNow(28),
    commercialStatus: "relationship_pending",
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111102",
    title: "PRINCE2 Foundation Training Cohort",
    provider: "Skills North UK",
    category: "certification",
    description: "Discounted project-delivery certification preparation for graduates and career changers.",
    routes: ["student", "graduate", "skilled_worker", "family_dependant"],
    cities: "all",
    goalTags: ["career", "certification", "project management"],
    trustScore: 0.86,
    readinessRequirements: [],
    deadline: daysFromNow(45),
    commercialStatus: "commission_embedded",
    commissionMinor: 2500,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111103",
    title: "NHS International Career Progression Webinar",
    provider: "Regional NHS Careers Hub",
    category: "event",
    description: "Free webinar on progression, professional development and sponsorship-aware career planning.",
    routes: ["health_care", "skilled_worker", "student", "graduate"],
    cities: "all",
    goalTags: ["healthcare", "career", "sponsorship"],
    trustScore: 0.98,
    readinessRequirements: [],
    deadline: daysFromNow(18),
    commercialStatus: "public_interest",
    sourceUrl: "https://www.healthcareers.nhs.uk/",
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111104",
    title: "UK Migrant Founder Validation Accelerator",
    provider: "Foundry North",
    category: "accelerator",
    description: "A twelve-week validation programme for founders building scalable UK products.",
    routes: ["founder", "global_talent", "graduate"],
    cities: ["London", "Leeds", "Manchester", "Birmingham"],
    goalTags: ["founder", "innovation", "evidence"],
    trustScore: 0.89,
    readinessRequirements: ["founder_evidence"],
    deadline: daysFromNow(35),
    commercialStatus: "commission_embedded",
    commissionMinor: 6000,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111105",
    title: "Local School Admissions Information Session",
    provider: "City Family Welcome Network",
    category: "family",
    description: "A free session for families navigating local school applications and term timelines.",
    routes: ["family_dependant", "skilled_worker", "health_care", "founder", "student"],
    cities: "all",
    goalTags: ["family", "school", "settlement"],
    trustScore: 0.94,
    readinessRequirements: [],
    deadline: daysFromNow(12),
    commercialStatus: "public_interest",
    sourceUrl: "https://www.gov.uk/schools-admissions",
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111106",
    title: "Graduate Professional Network Membership",
    provider: "UK Early Careers Network",
    category: "professional_network",
    description: "Peer events, mentoring and employer introductions for international graduates.",
    routes: ["student", "graduate", "family_dependant"],
    cities: "all",
    goalTags: ["network", "career", "job"],
    trustScore: 0.84,
    readinessRequirements: [],
    commercialStatus: "sponsored",
    sponsoredLabel: "Sponsored placement",
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111107",
    title: "Tenancy Rights and Housing Safety Clinic",
    provider: "Community Housing Advice Centre",
    category: "regulated_service",
    description: "General tenancy information and referral to qualified support where needed.",
    routes: "all",
    cities: ["Leeds", "Bradford", "Wakefield"],
    goalTags: ["housing", "safety", "settlement"],
    trustScore: 0.96,
    readinessRequirements: [],
    deadline: daysFromNow(21),
    commercialStatus: "public_interest",
    sourceUrl: "https://www.citizensadvice.org.uk/housing/",
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111108",
    title: "New-to-UK Digital Current Account",
    provider: "Harbour Bank",
    category: "banking",
    description: "A current-account option with a new-to-UK document checklist. Beginly does not provide financial advice.",
    routes: "all",
    cities: "all",
    goalTags: ["banking", "settlement"],
    trustScore: 0.82,
    readinessRequirements: [],
    commercialStatus: "commission_embedded",
    commissionMinor: 1800,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111109",
    title: "Workplace English Practice Group",
    provider: "Community Learning UK",
    category: "training",
    description: "Free weekly communication practice for work and professional settings.",
    routes: "all",
    cities: "all",
    goalTags: ["english", "job", "confidence"],
    trustScore: 0.93,
    readinessRequirements: [],
    commercialStatus: "public_interest",
    verifiedAt: new Date().toISOString(),
  },
  {
    id: "11111111-1111-4111-8111-111111111110",
    title: "Care Certificate Assessment Support",
    provider: "Care Skills Partnership",
    category: "training",
    description: "Structured assessment preparation for care workers building UK evidence and progression.",
    routes: ["health_care", "student", "family_dependant"],
    cities: "all",
    goalTags: ["healthcare", "care", "career"],
    trustScore: 0.88,
    readinessRequirements: ["career_journey"],
    deadline: daysFromNow(60),
    commercialStatus: "relationship_pending",
    verifiedAt: new Date().toISOString(),
  },
];

export const getProduct = (id: string): ProductDefinition | undefined => PRODUCTS.find((product) => product.id === id);
export const getCapability = (code: string): CapabilityDefinition | undefined => CAPABILITIES.find((capability) => capability.code === code);
