"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export default function HouseholdMemberActions({ memberId, role, privateWorkspace }: { memberId: string; role: string; privateWorkspace: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function patch(body: Record<string, unknown>) { setBusy(true); setMessage(""); const response = await fetch(`/api/platform/household/members/${memberId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...body, idempotencyKey: crypto.randomUUID() }) }); const data = await response.json(); setBusy(false); setMessage(response.ok ? "Household access updated." : data.error?.message ?? "Update failed."); if (response.ok) router.refresh(); }
  async function remove() { if (!window.confirm("Remove this member's household access? Their personal account is not deleted.")) return; setBusy(true); const response = await fetch(`/api/platform/household/members/${memberId}`, { method: "DELETE" }); const data = await response.json(); setBusy(false); setMessage(response.ok ? "Household access removed." : data.error?.message ?? "Removal failed."); if (response.ok) router.refresh(); }
  return <div className="member-action-panel"><button disabled={busy} onClick={() => patch({ action: "set_role", role: role === "partner" ? "adult_dependant" : "partner" })}>{role === "partner" ? "Set as adult dependant" : "Set as partner"}</button><button disabled={busy} onClick={() => patch({ action: "set_visibility", privateWorkspace: !privateWorkspace, dataVisibility: { shared_tasks: true, private_career: !privateWorkspace } })}>{privateWorkspace ? "Use shared workspace" : "Protect private workspace"}</button><button disabled={busy} onClick={() => patch({ action: "transfer_primary" })}>Transfer primary role</button><button disabled={busy} onClick={remove}>Remove access</button>{message && <small aria-live="polite">{message}</small>}</div>;
}
