"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type View = { status: "not_subscribed" | "active" | "paused" | "cancelled"; currentPeriodEnd?: string; providerManaged: boolean; latestAction?: { action: string; effectiveAt?: string } };
export default function SubscriptionControls({ productId, recurring, alternatives }: { productId: string; recurring: boolean; alternatives: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [view, setView] = useState<View | null>(null); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [replacement, setReplacement] = useState(alternatives[0]?.id ?? "");
  useEffect(() => { if (recurring) fetch(`/api/platform/subscriptions/${productId}`, { cache: "no-store" }).then((response) => response.json()).then(setView).catch(() => setMessage("Subscription status could not be loaded.")); }, [productId, recurring]);
  async function act(action: "pause" | "resume" | "cancel" | "replace") { if (action === "cancel" && !window.confirm("Cancel this subscription? Your completed work remains available, but subscription capabilities will end at the stated effective time.")) return; setBusy(action); setMessage(""); try { const response = await fetch(`/api/platform/subscriptions/${productId}`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ action, replacementProductId: action === "replace" ? replacement : undefined, reasonCodes: ["user_controlled_reconfiguration"] }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message ?? "The subscription could not be updated."); if (data.href) { router.push(data.href); return; } setMessage(data.state === "queued" ? "Your request is queued with the payment provider. Completed work remains retained." : `Subscription ${action} recorded. Completed work remains retained.`); const refreshed = await fetch(`/api/platform/subscriptions/${productId}`, { cache: "no-store" }).then((result) => result.json()); setView(refreshed); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The subscription could not be updated."); } finally { setBusy(""); } }
  if (!recurring) return <div className="trust-panel"><h3>Work-product retention</h3><p>This is not a recurring subscription. Completed work remains available according to the product terms.</p></div>;
  return <div className="trust-panel"><h3>Subscription control</h3><p>Status: <strong>{view?.status?.replaceAll("_", " ") ?? "loading"}</strong>{view?.currentPeriodEnd ? ` · current period ends ${new Date(view.currentPeriodEnd).toLocaleDateString("en-GB")}` : ""}</p><div className="nia-actions">{view?.status === "active" && <button type="button" disabled={Boolean(busy)} onClick={() => void act("pause")}>{busy === "pause" ? "Pausing…" : "Pause"}</button>}{view?.status === "paused" && <button type="button" disabled={Boolean(busy)} onClick={() => void act("resume")}>{busy === "resume" ? "Resuming…" : "Resume"}</button>}{view?.status !== "cancelled" && <button type="button" disabled={Boolean(busy)} onClick={() => void act("cancel")}>{busy === "cancel" ? "Cancelling…" : "Cancel"}</button>}</div>{alternatives.length > 0 && <div><label>Replace with a more relevant product<select value={replacement} onChange={(event) => setReplacement(event.target.value)}>{alternatives.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="button" className="platform-secondary" disabled={Boolean(busy) || !replacement} onClick={() => void act("replace")}>{busy === "replace" ? "Preparing…" : "Review replacement"}</button></div>}<small>Nia may recommend pausing or replacing support when relevance changes. Beginly does not require subscription lock-in.</small>{message && <p role="status">{message}</p>}</div>;
}
