import type { MigrationRoute } from "@/lib/platform/types";
import { PUBLIC_GUIDES } from "./public-guides";
import { PUBLIC_CITIES } from "./public-cities";
import { PUBLIC_OPPORTUNITY_CATEGORIES } from "./public-opportunity-categories";
export const SITE_URL = "https://beginly.app";
export interface PublicRouteAuthority {slug:string;route:MigrationRoute;name:string;title:string;description:string;answer:string;audiences:string[];journey:string[];freeValue:string[];futureTransitions:string[];reviewedAt:string;nextReviewAt:string}
export const PUBLIC_ROUTES:PublicRouteAuthority[]=[
{slug:"student",route:"student",name:"Student",title:"Beginly for international students in the UK",description:"Adaptive settlement, study readiness, opportunity discovery and early career preparation that evolves beyond arrival.",answer:"Beginly helps an international student organise settlement, study and future career actions in one continuing journey.",audiences:["New and current international students","Students with dependants","Students preparing for graduation"],journey:["Arrival and essential setup","Academic and wellbeing readiness","Part-time work and opportunity safety","Graduation and career preparation"],freeValue:["Route-aware onboarding","Adaptive journey and reminders","Basic Nia guidance","Relevant opportunities","Readiness visibility"],futureTransitions:["Graduate career preparation","Sponsored employment readiness","Family progression","Founder exploration"],reviewedAt:"2026-07-12",nextReviewAt:"2026-10-12"},
{slug:"graduate",route:"graduate",name:"Graduate",title:"Beginly for graduates building UK career readiness",description:"A career-first Beginly entry with adaptive applications, opportunities, sponsorship preparation and continuing settlement context.",answer:"Graduates can enter Beginly directly through career or opportunity products without repeating settlement onboarding.",audiences:["Recent graduates","Graduate-route users","International job seekers"],journey:["Career profile and readiness","CV and interview actions","Opportunity shortlisting","Employment and route transition preparation"],freeValue:["Career-aware journey","Basic opportunity matching","Readiness gaps","Basic Nia guidance"],futureTransitions:["Employment progression","Skilled Worker preparation","Professional development","Family planning"],reviewedAt:"2026-07-12",nextReviewAt:"2026-10-12"},
{slug:"skilled-worker",route:"skilled_worker",name:"Skilled Worker",title:"Beginly for Skilled Worker households",description:"Settlement, household coordination, career progression and future-transition preparation without separate identity silos.",answer:"Beginly combines a worker’s personal progression with shared household actions while protecting each adult’s private workspace.",audiences:["Skilled Workers","Partners and dependants","Progressing professionals"],journey:["Settlement continuity","Employment and professional development","Household coordination","Long-term progression"],freeValue:["Adaptive route journey","Household-aware actions","Relevant opportunities","Readiness visibility"],futureTransitions:["Career advancement","Family changes","Long-term residence preparation","Founder or leadership goals"],reviewedAt:"2026-07-12",nextReviewAt:"2026-10-12"},
{slug:"health-and-care",route:"health_care",name:"Health and Care",title:"Beginly for Health and Care professionals",description:"Professional progression, household transition and relevant opportunity intelligence designed around a continuing UK journey.",answer:"Beginly helps Health and Care professionals coordinate settlement, career progression, family actions and relevant opportunities.",audiences:["Health and Care workers","Clinical and care-support professionals","Healthcare households"],journey:["Work and settlement continuity","Professional evidence and progression","Household coordination","Future career transitions"],freeValue:["Route-aware journey","Basic Nia guidance","Opportunity relevance","Household context"],futureTransitions:["Professional registration","Career progression","Family progression","Leadership or specialist pathways"],reviewedAt:"2026-07-12",nextReviewAt:"2026-10-12"},
{slug:"family",route:"family_dependant",name:"Family and Dependant",title:"Beginly for partners, families and dependants",description:"Shared household coordination with individual goals, private adult workspaces and age-appropriate access.",answer:"Beginly coordinates shared family actions without treating every household member as one undifferentiated account.",audiences:["Partners and spouses","Adult dependants","Families with children"],journey:["Household setup","Health, school and local actions","Individual career or study goals","Family progression"],freeValue:["Household-aware onboarding","Shared tasks","Private adult workspaces","Basic guidance"],futureTransitions:["Partner employment","Education","Family changes","Long-term integration"],reviewedAt:"2026-07-12",nextReviewAt:"2026-10-12"},
{slug:"founder",route:"founder",name:"Founder",title:"Beginly for migrant and international founders",description:"Founder evidence, opportunity intelligence, household context and progression planning inside the wider Beginly continuity model.",answer:"Founders can enter through an evidence or opportunity workspace while retaining access to Beginly’s free adaptive foundation.",audiences:["Early-stage founders","Innovation-led applicants","International entrepreneurs"],journey:["Founder profile and evidence","Validation and ecosystem opportunities","Readiness gaps","Business and personal transition continuity"],freeValue:["Founder-aware journey","Basic opportunity radar","Readiness visibility","Basic Nia guidance"],futureTransitions:["Validation evidence","Funding and partnerships","Team and household growth","Long-term business progression"],reviewedAt:"2026-07-12",nextReviewAt:"2026-10-12"}
];
export const getPublicRoute=(slug:string)=>PUBLIC_ROUTES.find(item=>item.slug===slug);
export const PUBLIC_PATHS=["/","/routes","/guides","/cities","/nhs","/products","/opportunity-categories","/partners/commission-readiness","/privacy-policy","/terms-of-service","/trust/methodology",...PUBLIC_ROUTES.map(item=>`/routes/${item.slug}`),...PUBLIC_GUIDES.map(item=>`/guides/${item.slug}`),...PUBLIC_CITIES.map(item=>`/cities/${item.slug}`),...PUBLIC_OPPORTUNITY_CATEGORIES.map(item=>`/opportunity-categories/${item.slug}`)];
